(let (defcustoms)
  (dolist (file (directory-files "/home/practicalli/projects/emacs/cider" t "\.el"))
    (unless (string-match-p "dir-locals" file)
      (with-current-buffer (find-file file)
        (goto-char (point-min))
        (while (re-search-forward "defcustom" nil t)
          (let ((custom (substring-no-properties (progn (paredit-forward 1)
                                                        (thing-at-point 'sexp))))
                (docstring (substring-no-properties (progn (paredit-forward 2)
                                                           (or (thing-at-point 'sexp)
                                                               "no docstring provided")))))
            (push (list (file-name-nondirectory file) custom docstring)
                  defcustoms))))))
  (with-current-buffer (get-buffer-create "*defcustoms-from-cider*")
    (erase-buffer)
    (dolist (dc defcustoms)
      (insert (car dc) " : " (cadr dc) " : " (caddr dc) "\n==============\n"))))
