#!/bin/sh

## A quick hack to deploy a generated website onto a Github repository, to be served as static content by github pages.  This is an example of a very bad shell script.

# This should only be run from the root of the gitbook project
# Replace the remote Github URL to use this on a different project

# Trigger a clean and new build
gitbook build .

touch _book/.nojekyll

# Add Practicalli favicon
cp -f images/favicon_io/favicon.ico _book/gitbook/images/favicon.ico

# Add Apple touch icon
cp -f images/favicon_io/apple-touch-icon.png _book/gitbook/images/apple-touch-icon-precomposed-152.png


# Deploy new build
cd _book && rm -rf .git && git init && git add . && git commit -m "initial commit" && git branch -m live gh-pages && git remote add practicalli git@github.com:practicalli/spacemacs.git && git push -f practicalli gh-pages
